# Copyright (c) 2015 VMware, Inc.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- include_tasks: vars.yml

- name: Get etcd version
  become: yes
  command: >
    {{ etcdctl_cmd_v3 }} v
  register: etcdctl

- set_fact:
    etcd_version: "{{ etcdctl.stdout | regex_replace('etcdctl version: (.*)\n.*', '\\1') }}"
