# Copyright (c) 2015 VMware, Inc.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  notify: Restart etcd

- name: Restart etcd
  service: name={{etcd_service}} state=restarted
  become: yes
